### ISSUE TITLE
[BUG] 数组越界

### ISSUE THREAD

**Issue by LINKlang** [AneryCoft/AutoXGP#8]
卡在创建XBox档案`session_id_match = re.search(r'sid=(.+?)&',login_in.history[2].headers["Location"])`代码，
![image](https://github.com/AneryCoft/AutoXGP/assets/116951234/4c11d121-572e-4fc1-804d-689e63dbd3eb)

**Comment by AneryCoft** [comment]
你的账号是不是已经设置了Xbox档案？

**Comment by LINKlang** [comment]
> 你的账号是不是已经设置了Xbox档案？

用的邮箱批发的随机全新邮箱

**Comment by AneryCoft** [comment]
> > 你的账号是不是已经设置了Xbox档案？
> 
> 用的邮箱批发的随机全新邮箱

你看下 https://github.com/AneryCoft/AutoXGP/commit/0e7b1ae9e2635b97be07f1249b7b9b4f6c8cfda0 这个是强行过去的，我不知道你的新邮箱什么成分，可能会导致没有创建Xbox用户名。但是这个问题我在新号没法复现
